# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  AR5_5_07L_W4C4A2_joint_1:
    has_velocity_limits: true
    max_velocity: 3.0543261909900763
    has_acceleration_limits: true
    max_acceleration: 5.0
  AR5_5_07L_W4C4A2_joint_2:
    has_velocity_limits: true
    max_velocity: 3.0543261909900763
    has_acceleration_limits: true
    max_acceleration: 5.0
  AR5_5_07L_W4C4A2_joint_3:
    has_velocity_limits: true
    max_velocity: 4.7123889803846897
    has_acceleration_limits: true
    max_acceleration: 5.0
  AR5_5_07L_W4C4A2_joint_4:
    has_velocity_limits: true
    max_velocity: 5.2359877559829888
    has_acceleration_limits: true
    max_acceleration: 5.0
  AR5_5_07L_W4C4A2_joint_5:
    has_velocity_limits: true
    max_velocity: 4.1887902047863905
    has_acceleration_limits: true
    max_acceleration: 5.0
  AR5_5_07L_W4C4A2_joint_6:
    has_velocity_limits: true
    max_velocity: 4.1887902047863905
    has_acceleration_limits: true
    max_acceleration: 5.0
  AR5_5_07L_W4C4A2_joint_7:
    has_velocity_limits: true
    max_velocity: 4.1887902047863905
    has_acceleration_limits: true
    max_acceleration: 5.0
  lh_index_mcp_pitch:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  lh_middle_mcp_pitch:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  lh_pinky_mcp_pitch:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  lh_ring_mcp_pitch:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  lh_thumb_cmc_pitch:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  lh_thumb_cmc_yaw:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  lh_thumb_ip:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 5.0