# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - AR5_5_07L_W4C4A2_joint_1
      - AR5_5_07L_W4C4A2_joint_2
      - AR5_5_07L_W4C4A2_joint_3
      - AR5_5_07L_W4C4A2_joint_4
      - AR5_5_07L_W4C4A2_joint_5
      - AR5_5_07L_W4C4A2_joint_6
      - AR5_5_07L_W4C4A2_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

hand_controller:
  ros__parameters:
    joints:
      - lh_index_mcp_pitch
      - lh_middle_mcp_pitch
      - lh_pinky_mcp_pitch
      - lh_ring_mcp_pitch
      - lh_thumb_cmc_yaw
      - lh_thumb_cmc_pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
